//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSupportFeedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackEntryInfo
    {
        public System.Guid Id { get; set; }
        public string Source { get; set; }
        public int LogEntryLevel { get; set; }
        public int EventId { get; set; }
        public string Message { get; set; }
        public string Browser { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string Version { get; set; }
        public string SerialNumber { get; set; }
        public int OccuranceCount { get; set; }
        public System.Guid EntryId { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual FeedbackEntry FeedbackEntry { get; set; }
    }
}
