//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSupportFeedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MutedFeedbackEntry
    {
        public System.Guid Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Version { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.Guid> EntryId { get; set; }
        public bool UnMuted { get; set; }
        public bool HideFromView { get; set; }
    
        public virtual FeedbackEntry FeedbackEntry { get; set; }
    }
}
